FROM ubuntu:noble

RUN echo "root:root" | chpasswd

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk wget ssh openssh-server vim sudo telnet iputils-ping curl zip unzip
    
RUN useradd -m  hiveuser
RUN echo "hiveuser:hive" | chpasswd


USER hiveuser

WORKDIR /home/hiveuser

RUN wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz && \
    tar -xzf hadoop-3.4.1.tar.gz && \
    mv hadoop-3.4.1 hadoop && \
    rm hadoop-3.4.1.tar.gz

RUN wget -q https://archive.apache.org/dist/hive/hive-2.3.9/apache-hive-2.3.9-bin.tar.gz && \
    tar -xzf apache-hive-2.3.9-bin.tar.gz && \
    mv apache-hive-2.3.9-bin hive && \
    rm apache-hive-2.3.9-bin.tar.gz

# RUN mkdir -p /home/hiveuser/.ssh && \
#     ssh-keygen -t rsa -P '' -f /home/hiveuser/.ssh/id_rsa && \
#     cat /home/hiveuser/.ssh/id_rsa.pub >> /home/hiveuser/.ssh/authorized_keys && \
#     chmod 600 /home/hiveuser/.ssh/authorized_keys && \
#     chown -R hiveuser:hiveuser /home/hiveuser/.ssh


RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'>>/home/hiveuser/hadoop/etc/hadoop/hadoop-env.sh
RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'>>~/.bashrc

RUN echo 'export HADOOP_HOME=/home/hiveuser/hadoop'>>~/.bashrc
RUN echo 'export PATH=$PATH:$HADOOP_HOME/sbin' >> ~/.bashrc
RUN echo 'export PATH=$PATH:$HADOOP_HOME/bin' >> ~/.bashrc

RUN echo 'export HIVE_HOME=/home/hiveuser/hive' >> ~/.bashrc

RUN echo 'export PATH=$PATH:$HIVE_HOME/bin' >> ~/.bashrc

COPY config/hive_metastore/hive-site.xml hive/conf/hive-site.xml

ENV HIVE_HOME=/home/hiveuser/hive

RUN wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.20/mysql-connector-java-8.0.20.jar && \
    mv mysql-connector-java-8.0.20.jar $HIVE_HOME/lib/

USER root
COPY config/hive_metastore/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]