
services:
  trino-coordinator:
    build:
      context: ./trino
      dockerfile: trino.dockerfile
    image: trino-with-s3a
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8081:8080"
    volumes:
      - ../config/trino/coordinator/etc:/etc/trino
    networks:
      - reddit_network


  trino-worker-1:
    image: trino-with-s3a
    container_name: trino-worker-1
    hostname: trino-worker-1
    volumes:
      - ../config/trino/worker1/etc:/etc/trino
    networks:
      - reddit_network

  trino-worker-2:
    image: trino-with-s3a
    container_name: trino-worker-2
    hostname: trino-worker-2
    volumes:
      - ../config/trino/worker2/etc:/etc/trino
    networks:
      - reddit_network


networks:
  reddit_network:
    external: true
